---
ID: "c6bb96d4-d3dd-45de-9040-22219cd07255"
Parent: "ff5a748f-f921-4435-9c18-bd866dea2c91"
Template: "ff5a748f-f921-4435-9c18-bd866dea2c91"
Path: /sitecore/templates/Feature/TAC/Rendering Parameters/Common Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240809T184157Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\amandeep.singh@nypa.gov
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\amandeep.singh@nypa.gov
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0cb7273b-48d4-4653-a2e3-16fc5374cfa3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amandeep.singh@nypa.gov
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240809T184157Z
